global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - alertrules.yml

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_get]
    static_configs:
      - targets:
          - app:5050
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'flask-api'
    static_configs:
      - targets: ['app:5050']
    metrics_path: '/metrics'